name: EAS Staging Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        default: 'ios'
        type: choice
        options:
        - ios
        - android
        - both

jobs:
  build:
    name: Build Staging
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cli-version: latest

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build for staging (iOS)
        if: ${{ inputs.platform == 'ios' || inputs.platform == 'both' }}
        run: |
          cd apps/expo
          eas build --platform ios --profile staging --non-interactive

      - name: Build for staging (Android)
        if: ${{ inputs.platform == 'android' || inputs.platform == 'both' }}
        run: |
          cd apps/expo
          eas build --platform android --profile staging --non-interactive

      - name: Submit to App Store (staging)
        if: ${{ inputs.platform == 'ios' || inputs.platform == 'both' }}
        run: |
          cd apps/expo
          eas submit --platform ios --profile staging --non-interactive

      - name: Submit to Google Play (staging)
        if: ${{ inputs.platform == 'android' || inputs.platform == 'both' }}
        run: |
          cd apps/expo
          eas submit --platform android --profile staging --non-interactive
